name: Migrate V2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Restart migrate service
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "docker service update --force aredl_backend_stack_migrate"

      - name: Cleanup SSH key
        if: always()
        run: rm -rf ~/.ssh
